---
- name: Creates backup directory ...
  file: path={{ backup_dir }} state=directory
#  check_mode: yes
#  when: ansible_distribution == 'centos'

- name: Creates a file ...
  file: path={{ path_name }} state=touch  # (empty file create)
#  check_mode: yes

- name: file with content
  copy: src={{ src_path }} dest={{dest_path }}
#  check_mode: yes

- name: Restarting apapche
  service: name={{ service_name }} state={{ sataus_name }} enabled=yes

- name: Creates New directory ...
  file: path={{ backup1_dir }} state=directory

#- name: Created multiple user a single playbook
#  user: name={{ item_name }} state=present
#  with_items:
#    - { name: 'testuser1' }
#    - { name: 'testuser2' }

- name: Shell command
  shell: ls -lrt > /tmp/temp.txt

- name: create files using command
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - /tmp/diritory
    - /tmp/anotiihe

#- name: zip a folder  (use greater then ansible version 2 )
#  archive: path=/tmp/data dest=/tmp/data.tar.gz

#- name: Unarchive a file that is already on the remote machine
#  unarchive:
#    src: /tmp/data.tar.gz
#    dest: /opt/data

- name: unpack
  command: tar -xvf /tmp/data.tar.gz
