---
- name: Include OS Specific setup tasks
  include: "{{ ansible_os_family }}.yml"



#tasks for nginx setup


# Include variables on the basis of Operating System
#- name: Include OS-specific variables.
#  include_vars: "{{ ansible_distribution }}.yml"
#  include_vars: "{{ ansible_os_family }}.yml"
#  tags: include_variables

# Running Task for Debian Platform   
#- include: setup-Ubuntu.yml
#  when: ansible_distribution == 'Ubuntu'
#  when: ansible_os_family == 'Ubuntu'
#  tags: task_debian

# Running Task for Redhat Platform
#- include: setup-RedHat.yml
#  when: ansible_os_family == 'RedHat'
